=== CharlyDavid/Clase/E2/seleccionar lenguaje de marca XHTML 5/Documento XHTML5/DTD/parkour.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generado con XMLSpy v2019 rel. 3 sp1 (http://www.altova.com) -->
<!ELEMENT edad (#PCDATA)>
<!ELEMENT años (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT Factor (#PCDATA)>
<!ELEMENT apkadd (entidad, deporte, localidad, municipio, actitudes, juntadirectiva, miembros, eventos, entrenamientos, lugares, parkour, modalidad, Factor, historia, años, precursorbase, segundoprecursor, inplementadores, lugar, Indumentaria, calzado, pantalon, camiseta, saltos, recepciones, movimientos, movimietosavanzado, Practicantes, edad, practica, filosofia, valores, actualidad)>
<!ELEMENT saltos EMPTY>
<!ELEMENT calzado (#PCDATA)>
<!ELEMENT deporte (#PCDATA)>
<!ELEMENT entidad (#PCDATA)>
<!ELEMENT eventos EMPTY>
<!ELEMENT lugares EMPTY>
<!ELEMENT parkour EMPTY>
<!ELEMENT valores (#PCDATA)>
<!ELEMENT camiseta (#PCDATA)>
<!ELEMENT historia (#PCDATA)>
<!ELEMENT miembros EMPTY>
<!ELEMENT pantalon (#PCDATA)>
<!ELEMENT practica (#PCDATA)>
<!ELEMENT actitudes (#PCDATA)>
<!ELEMENT filosofia EMPTY>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT modalidad (#PCDATA)>
<!ELEMENT municipio EMPTY>
<!ELEMENT actualidad (#PCDATA)>
<!ELEMENT movimientos EMPTY>
<!ELEMENT recepciones EMPTY>
<!ELEMENT Indumentaria (#PCDATA)>
<!ELEMENT Practicantes (#PCDATA)>
<!ELEMENT precursorbase (#PCDATA)>
<!ELEMENT entrenamientos EMPTY>
<!ELEMENT juntadirectiva EMPTY>
<!ELEMENT inplementadores (#PCDATA)>
<!ELEMENT segundoprecursor (#PCDATA)>
<!ELEMENT movimietosavanzado EMPTY>

=== CharlyDavid/Clase/E2/seleccionar lenguaje de marca XHTML 5/Documento XHTML5/DTD/parkour.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE apkadd SYSTEM "C:\Users\USER\Documents\Deivid\Curso desarollo de app web - copia\clase\UF1841\E2\Pagina web asociacion\Examen\Documento XHTML5\DTD\parkour.dtd">
<apkadd>
	<entidad>Asociacion deportive</entidad>
	<deporte>Parkour arte del desplazamiento</deporte>
	<localidad> Tenerife </localidad>
	<municipio/>
	<actitudes>practica y difusion del parkour</actitudes>
	<juntadirectiva/>
	<miembros/>
	<eventos/>
	<entrenamientos/>
	<lugares/>
	<parkour/>
	<modalidad>Deporte</modalidad>
	<Factor>Deporte con factor de riesgo</Factor>
	<historia>Desarrollo de la historia</historia>
	<a単os>1900/2005</a単os>
	<precursorbase>Georges Hebert</precursorbase>
	<segundoprecursor>Raymon belle</segundoprecursor>
	<inplementadores> David belle y Yamakazy</inplementadores>
	<lugar>Nacido en Francia</lugar>
	<Indumentaria>Ropa</Indumentaria>
	<calzado>Tenis deportivos</calzado>
	<pantalon>largo o corto</pantalon>
	<camiseta>larga o corta</camiseta>
	<saltos/>
	<recepciones/>
	<movimientos/>
	<movimietosavanzado/>
	<Practicantes>hombre y mujer</Practicantes>
	<edad>recomendada 6 o 7 a単os en adelante</edad>
	<practica>lugar de practica</practica>
	<filosofia/>
	<valores>ense単anza a nivel personal</valores>
	<actualidad>panorama actual del deporte</actualidad>
</apkadd>
